In [1]:
from typing import List, Dict, Set, Any, Optional, Tuple, Literal, Callable
import numpy as np
import torch
from torch import Tensor
import sigkernel
import os
import sys
import tslearn
import tslearn.metrics
import ksig

from kernels.abstract_base import TimeSeriesKernel, StaticKernel
from kernels.static_kernels import LinearKernel, RBFKernel, PolyKernel
from kernels.integral import StaticIntegralKernel
from kernels.sig_pde import SigPDEKernel
from kernels.sig_trunc import TruncSigKernel
from kernels.gak import GlobalAlignmentKernel, sigma_gak

In [10]:
import ksig
import timeit

#### Test GAK ####
N=800
N2= 900
T, d = 8, 2
torch.manual_seed(0)
X = torch.randn(N, T, d, dtype=torch.float64).to("cuda") / d
Y = torch.randn(N2, T, d, dtype=torch.float64).to("cuda") / d
X_np = X.cpu().numpy()
Y_np = Y.cpu().numpy()

sigma = tslearn.metrics.sigma_gak(X_np)
gak = tslearn.metrics.cdist_gak
ksigker = ksig.kernels.GlobalAlignmentKernel(static_kernel=ksig.static.kernels.RBFKernel(bandwidth=sigma))
mine = GlobalAlignmentKernel(RBFKernel(sigma=sigma), normalize=False, )
# ksigker = ksig.kernels.SignatureKernel(static_kernel=ksig.static.kernels.RBFKernel(bandwidth=sigma), n_levels=5, order=1)
# mine = TruncSigKernel(RBFKernel(sigma=sigma), normalize=True, trunc_level=5, geo_order=1)


#out = gak(X, X, sigma=sigma)
out2 = ksigker(X_np, X_np)
print(out2)
out3 = mine(X, X)
#print(out)
print(out3)
print(np.mean(np.abs(out2 - out3.cpu().numpy())))

def function1():
    gak(X, X, sigma=sigma)

def function2():
    ksigker(X_np, X_np)

def function3():
    with torch.no_grad():
        mine(X, X)

# # Measure the execution time of function 1
# execution_time1 = timeit.timeit(function1, number=1)

# Measure the execution time of function 2
execution_time2 = timeit.timeit(function2, number=1)
print("Execution time of function 2:", execution_time2)
# Measure the execution time of function 3
execution_time3 = timeit.timeit(function3, number=1)
print("Execution time of function 3:", execution_time3)

[[1.         0.42993635 0.44140257 ... 0.38899524 0.48221973 0.27122034]
 [0.42993635 1.         0.66332664 ... 0.40233414 0.67158476 0.33839857]
 [0.44140257 0.66332664 1.         ... 0.39208809 0.52338122 0.4064439 ]
 ...
 [0.38899524 0.40233414 0.39208809 ... 1.         0.47092104 0.25732391]
 [0.48221973 0.67158476 0.52338122 ... 0.47092104 1.         0.46302038]
 [0.27122034 0.33839857 0.4064439  ... 0.25732391 0.46302038 1.        ]]
tensor([[1.0000, 0.4299, 0.4414,  ..., 0.3890, 0.4822, 0.2712],
        [0.4299, 1.0000, 0.6633,  ..., 0.4023, 0.6716, 0.3384],
        [0.4414, 0.6633, 1.0000,  ..., 0.3921, 0.5234, 0.4064],
        ...,
        [0.3890, 0.4023, 0.3921,  ..., 1.0000, 0.4709, 0.2573],
        [0.4822, 0.6716, 0.5234,  ..., 0.4709, 1.0000, 0.4630],
        [0.2712, 0.3384, 0.4064,  ..., 0.2573, 0.4630, 1.0000]],
       device='cuda:0', dtype=torch.float64)
4.462195586987794e-16
Execution time of function 2: 0.30644297300023027
Execution time of function 3: 31.86103888

In [ ]:
#### test dimensions of TimeSeriesKernels ####

N=3
N2=4
T, d = 40, 5
X = torch.randn(N, T, d, dtype=torch.float64) / d
Y = torch.randn(N2, T, d, dtype=torch.float64) / d

inputs = [
    (X, X),
    (X, Y),
    (X[0], X[0]),
    (X[0], Y[0]),
    (X[0], Y),
    (X, Y[0]),
]
diag_inputs = [
    (X, X),
    (X, Y[:N]),
    (X[0], X[0]),
    (X[0], Y[0]),
]
def test_kernel(ker: TimeSeriesKernel, inputs, diag=False):
    print(ker)
    for X, Y in inputs:
        out = ker(X, Y, diag, normalize=False)
        out_normalize = ker(X, Y, diag, normalize=True)
        print(out)
        print(out_normalize)
        print(out.shape)
    print()


sigker = TruncSigKernel(static_kernel=RBFKernel(), 
                        trunc_level=4, 
                        geo_order=1,
                        only_last=True,)
test_kernel(sigker, inputs)
test_kernel(sigker, diag_inputs, True)

sigpde = SigPDEKernel(static_kernel=RBFKernel(),
                     dyadic_order=3,)
test_kernel(sigpde, inputs)
test_kernel(sigpde, diag_inputs, True)

intker = StaticIntegralKernel(static_kernel=RBFKernel())
test_kernel(intker, inputs)
test_kernel(intker, diag_inputs, True)

In [ ]:
import numpy as np
import ksig

# Number of signature levels to use.
n_levels = 5 

# Use the RBF kernel for vector-valued data as static (base) kernel.
static_kernel = ksig.static.kernels.RBFKernel() 

# Instantiate the signature kernel, which takes as input the static kernel.
n_levels = 5
order = 1
sig_kernel = ksig.kernels.SignatureKernel(n_levels=n_levels, order=order, static_kernel=static_kernel)

# Generate 10 sequences of length 50 with 5 channels.
n_seq, l_seq, n_feat = 10, 50, 5 
X = np.random.randn(n_seq, l_seq, n_feat)

# Sequence kernels take as input an array of sequences of ndim == 3,
# and work as a callable for computing the kernel matrix. 
K_XX = sig_kernel(X)  # K_XX has shape (10, 10).

# The diagonal kernel entries can also be computed.
K_X = sig_kernel(X, diag=True)  # K_X has shape (10,).

# Generate another array of 8 sequences of length 20 and 5 features.
n_seq2, l_seq2 = 8, 20
Y = np.random.randn(n_seq2, l_seq2, n_feat)

# Compute the kernel matrix between arrays X and Y.
K_XY = sig_kernel(X, Y)  # K_XY has shape (10, 8)
K_XY